// Purpose: Member model for group members
// Author: Generated

class GroupMember {
  final String id;
  final GroupMemberUser user;
  final String joinDate;
  final String status; // 'active', 'pending', 'removed'
  final int? turnPosition;
  final int? trustScoreAtJoin;
  final bool isAutoGenerated;

  GroupMember({
    required this.id,
    required this.user,
    required this.joinDate,
    required this.status,
    this.turnPosition,
    this.trustScoreAtJoin,
    required this.isAutoGenerated,
  });

  factory GroupMember.fromJson(Map<String, dynamic> json) {
    return GroupMember(
      id: json['id'] as String,
      user: GroupMemberUser.fromJson(json['user'] as Map<String, dynamic>),
      joinDate: json['join_date'] as String,
      status: json['status'] as String? ?? 'active',
      turnPosition: json['turn_position'] as int?,
      trustScoreAtJoin: json['trust_score_at_join'] as int?,
      isAutoGenerated: json['is_auto_generated'] as bool? ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'user': user.toJson(),
      'join_date': joinDate,
      'status': status,
      'turn_position': turnPosition,
      'trust_score_at_join': trustScoreAtJoin,
      'is_auto_generated': isAutoGenerated,
    };
  }
}

class GroupMemberUser {
  final String id;
  final String phone;
  final String? email;
  final String fullName;
  final String? workStatus;
  final String? profilePicUrl;
  final int trustScore;
  final String kycStatus;
  final bool isActive;
  final List<dynamic> roles;
  final String createdAt;

  GroupMemberUser({
    required this.id,
    required this.phone,
    this.email,
    required this.fullName,
    this.workStatus,
    this.profilePicUrl,
    required this.trustScore,
    required this.kycStatus,
    required this.isActive,
    required this.roles,
    required this.createdAt,
  });

  factory GroupMemberUser.fromJson(Map<String, dynamic> json) {
    return GroupMemberUser(
      id: json['id'] as String,
      phone: json['phone'] as String,
      email: json['email'] as String?,
      fullName: json['full_name'] as String,
      workStatus: json['work_status'] as String?,
      profilePicUrl: json['profile_pic_url'] as String?,
      trustScore: json['trust_score'] as int? ?? 0,
      kycStatus: json['kyc_status'] as String? ?? 'not_started',
      isActive: json['is_active'] as bool? ?? true,
      roles: json['roles'] as List<dynamic>? ?? [],
      createdAt: json['created_at'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'phone': phone,
      'email': email,
      'full_name': fullName,
      'work_status': workStatus,
      'profile_pic_url': profilePicUrl,
      'trust_score': trustScore,
      'kyc_status': kycStatus,
      'is_active': isActive,
      'roles': roles,
      'created_at': createdAt,
    };
  }
}
