import 'package:get/get.dart';
import '../models/group_model.dart';
import '../models/member_model.dart';
import 'dart:async';

class InKindDetailController extends GetxController {
  final InKindGroup group;
  final RxInt activeTab = 0.obs;
  final RxBool showAllMembers = false.obs;
  final RxList<GroupMember> members = <GroupMember>[].obs;
  final RxList payments = [].obs;
  final RxList history = [].obs;
  final RxBool isMembersLoading = false.obs;
  final RxBool isPaymentsLoading = false.obs;
  final RxBool isHistoryLoading = false.obs;

  InKindDetailController({required this.group});

  @override
  void onInit() {
    super.onInit();
    loadMembers();
    loadPayments();
    loadHistory();
  }

  void setActiveTab(int tabIndex) {
    activeTab.value = tabIndex;
  }

  void toggleShowAllMembers() {
    showAllMembers.value = !showAllMembers.value;
  }

  Future<void> loadMembers() async {
    isMembersLoading.value = true;
    try {
      // Simulate API call to load members
      await Future.delayed(
        const Duration(seconds: 1),
      ); // Simulate network delay

      // Mock data for demonstration
      members.assignAll([
        GroupMember(
          id: '1',
          user: GroupMemberUser(
            id: 'user1',
            phone: '+251912345678',
            email: 'john@example.com',
            fullName: 'John Doe',
            workStatus: null,
            profilePicUrl: null,
            trustScore: 80,
            kycStatus: 'verified',
            isActive: true,
            roles: [],
            createdAt: DateTime.now().toIso8601String(),
          ),
          joinDate: DateTime.now()
              .subtract(const Duration(days: 10))
              .toIso8601String(),
          status: 'active',
          isAutoGenerated: false,
        ),
        GroupMember(
          id: '2',
          user: GroupMemberUser(
            id: 'user2',
            phone: '+251912345679',
            email: 'jane@example.com',
            fullName: 'Jane Smith',
            workStatus: null,
            profilePicUrl: null,
            trustScore: 75,
            kycStatus: 'pending',
            isActive: true,
            roles: [],
            createdAt: DateTime.now().toIso8601String(),
          ),
          joinDate: DateTime.now()
              .subtract(const Duration(days: 5))
              .toIso8601String(),
          status: 'pending',
          isAutoGenerated: false,
        ),
      ]);
    } catch (e) {
      // Handle error
    } finally {
      isMembersLoading.value = false;
    }
  }

  Future<void> loadPayments() async {
    isPaymentsLoading.value = true;
    try {
      // Simulate API call to load payments
      await Future.delayed(
        const Duration(seconds: 1),
      ); // Simulate network delay

      // Mock data for demonstration
      payments.assignAll([
        {
          'id': 'pay1',
          'amount': group.contributionAmount.toInt(),
          'member': 'John Doe',
          'date': DateTime.now()
              .subtract(const Duration(days: 14))
              .toString()
              .split(' ')[0],
          'status': 'paid',
          'item': group.inventoryItemName ?? 'In-kind item',
        },
        {
          'id': 'pay2',
          'amount': group.contributionAmount.toInt(),
          'member': 'Jane Smith',
          'date': DateTime.now()
              .subtract(const Duration(days: 7))
              .toString()
              .split(' ')[0],
          'status': 'paid',
          'item': group.inventoryItemName ?? 'In-kind item',
        },
      ]);
    } catch (e) {
      // Handle error
    } finally {
      isPaymentsLoading.value = false;
    }
  }

  Future<void> loadHistory() async {
    isHistoryLoading.value = true;
    try {
      // Simulate API call to load history
      await Future.delayed(
        const Duration(seconds: 1),
      ); // Simulate network delay

      // Mock data for demonstration
      history.assignAll([
        {
          'action': 'Group Created',
          'date':
              group.startDate?.toString().split(' ')[0] ??
              DateTime.now().toString().split(' ')[0],
          'initiator': 'You',
        },
        {
          'action': 'First Round Completed',
          'date': DateTime.now()
              .subtract(const Duration(days: 7))
              .toString()
              .split(' ')[0],
          'initiator': 'John Doe',
        },
        {
          'action': 'Second Round Completed',
          'date': DateTime.now()
              .subtract(const Duration(days: 1))
              .toString()
              .split(' ')[0],
          'initiator': 'Jane Smith',
        },
      ]);
    } catch (e) {
      // Handle error
    } finally {
      isHistoryLoading.value = false;
    }
  }

  Future<void> inviteToGroup() async {
    // Placeholder for invite functionality
    print('Inviting to group: ${group.name}');
  }
}
